version: "2"
services:
    dominio:
        image: crezcamos/dominio
        ports:
            - "8446:8446"
        restart: always
    negocio:
        image: crezcamos/logica
        ports:
            - "8449:8449"
        volumes:
            - /home/gestionamos/adjuntos:/adjuntos
            - /home/gestionamos/upload-dir:/upload-dir
        links:
            - dominio
        restart: always