version: "2"
services:
    dominio:
        image: crezcamos/dominio
        environment:
            PUERTO_SERVICIO: 8446
            HOST: bd-ciberdix.database.windows.net
        ports:
            - "8446:8446"
        restart: always
    negocio:
        image: crezcamos/logica
        environment:
            PUERTO_SERVICIO: 8449
            HOST: 52.168.77.111
            RECAPTCHA_URL: https://www.google.com/recaptcha/api/siteverify
        ports:
            - "8449:8449"
        volumes:
            - /home/administrador/adjuntos:/adjuntos
        links:
            - dominio
        restart: always