version: "2"
services:
    dominio:
        image: crezcamos/dominio
        environment:
            PUERTO_SERVICIO: 8446
            DB_HOST: 10.128.0.4:1433;databaseName=CREZCAMOS
            DB_USER: sa
            DB_PASSWORD: Sistemas2016
        ports:
            - "8446:8446"
        restart: always
    negocio:
        image: crezcamos/logica
        environment:
            PUERTO_SERVICIO: 8449
            HOST: 10.128.0.2
            RECAPTCHA_URL: https://www.google.com/recaptcha/api/siteverify
            FRONT_ADDRESS: 35.188.192.89
        ports:
            - "8449:8449"
        volumes:
            - /home/gestionamos/adjuntos:/adjuntos
            - /home/gestionamos/upload-dir:/upload-dir
        links:
            - dominio
        restart: always