---
server:
  port: 8449
spring:
  mvc:
    date-format: yyyy-mm-dd
  jackson:
    deserialization:
      adjust_dates_to_context_time_zone: false
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
url: http://40.71.92.147
front:
  address: http://40.71.92.147
  port: 5557
  url: ${front.address}:${front.port}
domain:
  port: 8446
  url: ${url}:${domain.port}
business:
  port: 8449
  url: ${url}:${business.port}
recaptcha:
  url: https://www.google.com/recaptcha/api/siteverify
policy:
  json:
    filePath: /some/file/goes/here
api:
  version: 1.0

---
server:
  port: ${PUERTO_SERVICIO}
spring:
  profiles: docker
  mvc:
    date-format: yyyy-mm-dd
  jackson:
    deserialization:
      adjust_dates_to_context_time_zone: false
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
url: http://${HOST}
front:
  address: http://${HOST}
  port: 5557
  url: ${front.address}:${front.port}
domain:
  port: 8446
  url: ${url}:${domain.port}
business:
  port: ${PUERTO_SERVICIO}
  url: ${url}:${business.port}
recaptcha:
  url: https://www.google.com/recaptcha/api/siteverify
policy:
  json:
    filePath: /some/file/goes/here
api:
  version: 1.0

