---
spring:
  datasource:
    url: jdbc:sqlserver://bd-ciberdix.database.windows.net;databaseName=CREZCAMOS
    username: vladeye
    password: LcdmaASqeme_2013
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: com.ciberdix.th.configuration.CiberdixSqlDialect
  jackson:
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      adjust_dates_to_context_time_zone: false
server:
  port: 8446

---
spring:
  profiles: docker
  datasource:
    url: jdbc:sqlserver://${HOST}:1433;databaseName=CREZCAMOS
    username: vladeye
    password: LcdmaASqeme_2013
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: com.ciberdix.th.configuration.CiberdixSqlDialect
  jackson:
    serialization:
      write_dates_as_timestamps: false
    deserialization:
      adjust_dates_to_context_time_zone: false
server:
  port: ${PUERTO_SERVICIO}